// TABLE NAMES
export const TABLE_NAMES = {
  USERS: "users",
  DEVICES: "devices",
  CMS: "cms",
  COMPANY: "company",
  FACILITY: "facility",
  CHILLER: "chiller",
  ProblemAndSolution: "problemAndSolutions",
  CHILLER_TIMELINE: "timeline",
  LOGS: "logs",
  MAINTENANCE_LOGS: "maintenanceLogs",
  BAD_LOGS: "badLogs",
  SCHEDULE_JOBS: "ScheduledJob",
  REPORTS: "reports",
  NOTIFICAIONS: "notifications",
  USER_ACTION_LOG: "userActionLog",
  HIST_CHILL_PERFORMANCE: "histChillerPerformance",
  HIST_FACILITY_PERFORMANCE: "histLocationPerformance",
  HIST_COMPANY_PERFORMANCE: "histCompanyPerformance",
};
